apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parsedmarc.fullname" . }}
  labels:
    {{- include "parsedmarc.labels" . | nindent 4 }}
type: Opaque
stringData:
  imap-password: {{ .Values.parsedmarc.imap.password | quote }}
  {{- if .Values.parsedmarc.smtp.password }}
  smtp-password: {{ .Values.parsedmarc.smtp.password | quote }}
  {{- end }}
  {{- if .Values.parsedmarc.splunk.token }}
  splunk-token: {{ .Values.parsedmarc.splunk.token | quote }}
  {{- end }}
